server:
  port: 8080
  servlet:
    context-path: /api/zorgundostu

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://zorgundostu-db:5432/zorgundostu
    username: postgres
    password: postgres
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
